### ISSUE TITLE
README 中 v1.0 时间年份错误

### ISSUE THREAD

**Issue by chinsyo** [oh-bear/elephant-food#1]
按照semver规范，demo通常是0.1.0 版本，时间应早于1.0.0版本

**Comment by airingursb** [comment]
@chinsyo  谢谢科普… 感谢关注

**Comment by chinsyo** [comment]
> @chinsyo 谢谢科普… 感谢关注

可是，你并没有改啊。。

**Comment by airingursb** [comment]
@chinsyo = = 谢谢关注，目前项目还在调研中，之后会逐步更新代码和文档的…_
